export const idlFactory = ({ IDL }) => {
  return IDL.Service({
    'assignAuditor' : IDL.Func([IDL.Nat, IDL.Principal], [IDL.Text], []),
    'cancelProposal' : IDL.Func([IDL.Nat], [IDL.Text], []),
    'distributeReward' : IDL.Func([IDL.Principal, IDL.Nat], [IDL.Text], []),
    'donate' : IDL.Func([IDL.Text], [IDL.Text], []),
    'getActiveAuditors' : IDL.Func([], [IDL.Text], ['query']),
    'getAuditor' : IDL.Func([IDL.Principal], [IDL.Text], ['query']),
    'getAuditorCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getOwner' : IDL.Func([], [IDL.Text], ['query']),
    'getPendingReward' : IDL.Func([IDL.Principal], [IDL.Nat], ['query']),
    'getProposal' : IDL.Func([IDL.Nat], [IDL.Text], ['query']),
    'getProposalCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getProposalsByChain' : IDL.Func([IDL.Nat], [IDL.Text], ['query']),
    'getProposalsByStatus' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
    'getProtocolBalance' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
    'getProtocolCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getProtocolTier' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
    'getReviewsForProposal' : IDL.Func([IDL.Nat], [IDL.Text], ['query']),
    'getTotalDistributed' : IDL.Func([IDL.Principal], [IDL.Nat], ['query']),
    'getTreasuryBalance' : IDL.Func([], [IDL.Nat], ['query']),
    'getVersion' : IDL.Func([], [IDL.Nat], ['query']),
    'prepareExecution' : IDL.Func([IDL.Nat], [IDL.Text], []),
    'reactivateAuditor' : IDL.Func([], [IDL.Text], []),
    'recordExecution' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Text], []),
    'registerAuditor' : IDL.Func([], [IDL.Text], []),
    'submitProposal' : IDL.Func([IDL.Text], [IDL.Text], []),
    'submitReview' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Text], []),
    'suspendAuditor' : IDL.Func([], [IDL.Text], []),
    'testEthBlockNumber' : IDL.Func([], [IDL.Text], []),
    'testEvmRpc' : IDL.Func([], [IDL.Text], []),
    'transferOwnership' : IDL.Func([IDL.Principal], [IDL.Text], []),
  });
};
export const init = ({ IDL }) => { return []; };
