||| Proposals Module
|||
||| Handles cross-chain upgrade proposal lifecycle and routing.
||| This module coordinates between:
||| - LazyEvmLifecycle (source of upgrade recommendations)
||| - AuditorPool (reviewer assignment)
||| - Rewards (fee/reward handling)
||| - EVM chains (execution via HttpOutcall)
module Proposals.Core

import FRMonad.Core
import OUC.Core
import Data.List

%default total

-- =============================================================================
-- Proposal Routing Types
-- =============================================================================

||| Source of proposal (for evidence tracking)
public export
data ProposalSource
  = LazyEvmLifecycle ChainId  -- Generated by lazy evm-lifecycle ask
  | DirectSubmission          -- Direct canister call
  | CrossCanisterCall String  -- From another canister

public export
Show ProposalSource where
  show (LazyEvmLifecycle c) = "LazyEvmLifecycle(" ++ show c ++ ")"
  show DirectSubmission     = "DirectSubmission"
  show (CrossCanisterCall c)= "CrossCanister(" ++ c ++ ")"

||| Evidence of proposal receipt from LazyEvmLifecycle
||| This is the key link: "upgrade推奨" ≡ "proposal到達"
public export
record ProposalReceipt where
  constructor MkProposalReceipt
  proposalId    : ProposalId
  source        : ProposalSource
  receivedAt    : Nat
  sourceEvidence: String       -- Evidence from source (txHash, etc.)
  ackSignature  : String       -- OUC signature acknowledging receipt

public export
Show ProposalReceipt where
  show r = "Receipt{" ++ show r.proposalId ++ " from " ++ show r.source ++ "}"

-- =============================================================================
-- Proposal Validation
-- =============================================================================

||| Validation result for proposals
public export
data ValidationResult
  = Valid
  | InvalidChain String
  | InvalidTarget String
  | InvalidOU String
  | InvalidImpl String
  | ExpiredProposal
  | DuplicateProposal

public export
Show ValidationResult where
  show Valid              = "Valid"
  show (InvalidChain s)   = "InvalidChain: " ++ s
  show (InvalidTarget s)  = "InvalidTarget: " ++ s
  show (InvalidOU s)      = "InvalidOU: " ++ s
  show (InvalidImpl s)    = "InvalidImpl: " ++ s
  show ExpiredProposal    = "ExpiredProposal"
  show DuplicateProposal  = "DuplicateProposal"

||| Chain configuration for validation
public export
record ChainConfig where
  constructor MkChainConfig
  chainId   : ChainId
  oufAddr   : EvmAddress    -- OptimisticUpgraderFactory
  oucAddr   : EvmAddress    -- OUC's address on this chain
  rpcUrl    : String
  isActive  : Bool

-- =============================================================================
-- Proposal Operations (FRC-compliant)
-- =============================================================================

||| Validate a proposal against chain configuration
public export
validateProposal :
  UpgradeProposal ->
  List ChainConfig ->
  Nat ->                     -- currentTime
  FR ValidationResult
validateProposal proposal configs now =
  case find (\c => c.chainId == proposal.chainId) configs of
    Nothing => ok Query "validateProposal" "Chain not configured"
               (InvalidChain ("Unknown chain: " ++ show proposal.chainId))
    Just config =>
      if not config.isActive
        then ok Query "validateProposal" "Chain inactive"
             (InvalidChain "Chain is not active")
        else if now > proposal.expiresAt
          then ok Query "validateProposal" "Proposal expired"
               ExpiredProposal
          else ok Query "validateProposal" "Proposal valid" Valid

||| Receive proposal from LazyEvmLifecycle
||| This is the entry point that establishes "upgrade推奨 ≡ proposal到達"
public export
receiveFromLifecycle :
  OUCState ->
  ChainId ->
  EvmAddress ->              -- target
  EvmAddress ->              -- newImpl
  EvmAddress ->              -- ou
  ICPrincipal ->             -- proposer
  String ->                  -- rationale
  String ->                  -- codeHash
  String ->                  -- sourceEvidence (from LazyEvmLifecycle)
  Nat ->                     -- currentTime
  FR (OUCState, ProposalReceipt)
receiveFromLifecycle state chainId target newImpl ou proposer rationale codeHash srcEvid now = do
  (newState, pid) <- submitProposal state chainId target newImpl ou proposer rationale codeHash now
  let receipt = MkProposalReceipt pid (LazyEvmLifecycle chainId) now srcEvid ""
  ok Update "receiveFromLifecycle"
     ("Received proposal " ++ show pid ++ " from lifecycle")
     (newState, receipt)

||| Route proposal to auditor pool
public export
routeToAuditor :
  OUCState ->
  ProposalId ->
  AuditorId ->               -- Selected auditor
  Nat ->                     -- currentTime
  FR OUCState
routeToAuditor state pid aid now = do
  newState <- assignAuditor state pid aid now
  ok Update "routeToAuditor"
     ("Routed " ++ show pid ++ " to " ++ show aid)
     newState

||| Process review and update proposal status
public export
processReview :
  OUCState ->
  ProposalId ->
  AuditorId ->
  ReviewDecision ->
  String ->                  -- comment
  String ->                  -- signature
  Nat ->                     -- currentTime
  FR OUCState
processReview state pid aid decision comment sig now = do
  newState <- submitReview state pid aid decision comment sig now
  ok Update "processReview"
     ("Processed review for " ++ show pid ++ ": " ++ show decision)
     newState

-- =============================================================================
-- Cross-Chain Execution Types
-- =============================================================================

||| Execution request for approved proposal
public export
record ExecutionRequest where
  constructor MkExecutionRequest
  proposalId : ProposalId
  chainId    : ChainId
  target     : EvmAddress
  calldata   : String        -- Encoded upgrade calldata
  signature  : String        -- OUC (vetKey) signature authorizing execution
  deadline   : Nat           -- Execution deadline

public export
Show ExecutionRequest where
  show e = "ExecReq{" ++ show e.proposalId ++ " on " ++ show e.chainId ++ "}"

||| Execution result from EVM chain
public export
data ExecutionResult
  = ExecSuccess String              -- txHash
  | ExecReverted String             -- reason
  | ExecTimeout
  | ExecRpcError Int String         -- code, message

public export
Show ExecutionResult where
  show (ExecSuccess h)    = "Success: " ++ h
  show (ExecReverted r)   = "Reverted: " ++ r
  show ExecTimeout        = "Timeout"
  show (ExecRpcError c m) = "RpcError(" ++ show c ++ "): " ++ m

||| Prepare execution request for approved proposal
public export
prepareExecution :
  OUCState ->
  ProposalId ->
  Nat ->                     -- deadline
  FR ExecutionRequest
prepareExecution state pid deadline = do
  proposal <- findProposal state pid
  case proposal.status of
    Approved =>
      let req = MkExecutionRequest
            pid proposal.chainId proposal.target
            ""  -- Calldata would be encoded elsewhere
            ""  -- Signature would be added by signing service
            deadline
      in ok Update "prepareExecution"
            ("Prepared execution for " ++ show pid)
            req
    other =>
      fail Update "prepareExecution"
           ("Cannot execute " ++ show other ++ " proposal")
           (InvalidState "Proposal not approved")

||| Record execution result
public export
recordExecution :
  OUCState ->
  ProposalId ->
  ExecutionResult ->
  Nat ->                     -- currentTime
  FR OUCState
recordExecution state pid result now =
  case result of
    ExecSuccess txHash => do
      newState <- markExecuted state pid txHash now
      ok Update "recordExecution"
         ("Recorded success for " ++ show pid ++ ": " ++ txHash)
         newState
    ExecReverted reason =>
      fail Update "recordExecution"
           ("Execution reverted: " ++ reason)
           (CallError reason)
    ExecTimeout =>
      fail Update "recordExecution"
           "Execution timed out"
           (Timeout "HttpOutcall timeout")
    ExecRpcError code msg =>
      fail Update "recordExecution"
           ("RPC error: " ++ msg)
           (CallError ("RPC " ++ show code ++ ": " ++ msg))

-- =============================================================================
-- Proposal Statistics
-- =============================================================================

||| Get count of proposals by status
public export
countByStatus : OUCState -> ProposalStatus -> Nat
countByStatus state status = length (filter (\p => p.status == status) state.proposals)

||| Get all pending proposals for a chain
public export
getPendingForChain : OUCState -> ChainId -> List UpgradeProposal
getPendingForChain state chainId =
  filter (\p => p.chainId == chainId && p.status == Pending) state.proposals

||| Get proposals awaiting review
public export
getAwaitingReview : OUCState -> List UpgradeProposal
getAwaitingReview state = filter (\p => p.status == UnderReview) state.proposals

||| Get approved proposals ready for execution
public export
getApprovedForExecution : OUCState -> List UpgradeProposal
getApprovedForExecution state = filter (\p => p.status == Approved) state.proposals
