#!/bin/bash
# Build OUC Idris2 to ICP Canister WASM
# Pipeline: Idris2 → RefC → C → Emscripten → WASM → WASI stub → IC
set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
BUILD_DIR="$PROJECT_DIR/build"
IC0_SUPPORT="$PROJECT_DIR/support/ic0"

# Idris2 environment
export PATH="$HOME/.local/bin:$HOME/.pack/bin:$PATH"
export IDRIS2_PREFIX="${IDRIS2_PREFIX:-$HOME/.idris2}"

# Use emsdk if available
if [ -f "$HOME/emsdk/emsdk_env.sh" ]; then
    source "$HOME/emsdk/emsdk_env.sh" > /dev/null 2>&1
    echo "Using emsdk: $(emcc --version | head -1)"
fi

echo "=== Building OUC to ICP Canister WASM ==="

# Check dependencies
command -v idris2 >/dev/null 2>&1 || { echo "idris2 not found"; exit 1; }
command -v emcc >/dev/null 2>&1 || { echo "emcc not found. Install: https://emscripten.org/docs/getting_started/downloads.html"; exit 1; }

mkdir -p "$BUILD_DIR"

# =============================================================================
# Step 1: Compile Idris2 → C (RefC backend)
# =============================================================================
echo ">>> Step 1: Idris2 → C (RefC backend)"

cd "$PROJECT_DIR"

# Use RefC codegen to produce C code
# Note: We need to compile Main.idr which imports the entire OUC module tree
idris2 --codegen refc \
    --build-dir "$BUILD_DIR/idris" \
    -p contrib \
    --source-dir src \
    -o main \
    src/Main.idr 2>&1 || {
    echo "RefC compilation failed"
    exit 1
}

# Find generated C file
C_FILE=$(find "$BUILD_DIR/idris" -name "*.c" | head -1)
if [ -z "$C_FILE" ]; then
    echo "No C file generated by RefC"
    exit 1
fi
echo "Generated: $C_FILE"

# =============================================================================
# Step 2: Download RefC runtime dependencies
# =============================================================================
echo ">>> Step 2: Prepare RefC runtime"

# Idris2 RefC runtime location
IDRIS2_VERSION="${IDRIS2_VERSION:-0.8.0}"
IDRIS2_SUPPORT="${IDRIS2_PREFIX}/idris2-${IDRIS2_VERSION}/support"
REFC_SUPPORT="$IDRIS2_SUPPORT/refc"
C_SUPPORT="$IDRIS2_SUPPORT/c"

# If local support doesn't exist, download from GitHub
REFC_SRC="/tmp/refc-src"
MINI_GMP="/tmp/mini-gmp"

if [ ! -f "$REFC_SRC/runtime.c" ]; then
    echo "Downloading RefC runtime sources..."
    mkdir -p "$REFC_SRC"
    for f in memoryManagement.c runtime.c stringOps.c mathFunctions.c casts.c clock.c buffer.c prim.c refc_util.c; do
        curl -sLo "$REFC_SRC/$f" "https://raw.githubusercontent.com/idris-lang/Idris2/main/support/refc/$f"
    done
    for f in idris_support.c idris_file.c idris_directory.c idris_util.c; do
        curl -sLo "$REFC_SRC/$f" "https://raw.githubusercontent.com/idris-lang/Idris2/main/support/c/$f"
    done
fi

if [ ! -f "$MINI_GMP/mini-gmp.c" ]; then
    echo "Downloading mini-gmp..."
    mkdir -p "$MINI_GMP"
    curl -sLo "$MINI_GMP/mini-gmp.c" https://gmplib.org/repo/gmp/raw-file/tip/mini-gmp/mini-gmp.c
    curl -sLo "$MINI_GMP/mini-gmp.h" https://gmplib.org/repo/gmp/raw-file/tip/mini-gmp/mini-gmp.h
    cat > "$MINI_GMP/gmp.h" << 'GMPEOF'
#ifndef GMP_WRAPPER_H
#define GMP_WRAPPER_H
#include "mini-gmp.h"
#include <stdarg.h>
static inline void mpz_inits(mpz_t x, ...) {
    va_list ap; va_start(ap, x); mpz_init(x);
    while ((x = va_arg(ap, mpz_ptr)) != NULL) mpz_init(x);
    va_end(ap);
}
static inline void mpz_clears(mpz_t x, ...) {
    va_list ap; va_start(ap, x); mpz_clear(x);
    while ((x = va_arg(ap, mpz_ptr)) != NULL) mpz_clear(x);
    va_end(ap);
}
#endif
GMPEOF
fi

# Use local or downloaded sources
if [ -d "$REFC_SUPPORT" ]; then
    REFC_INCLUDE="$REFC_SUPPORT"
    C_INCLUDE="$C_SUPPORT"
else
    REFC_INCLUDE="$REFC_SRC"
    C_INCLUDE="$REFC_SRC"
fi

# Minimal RefC files for canister (no file I/O to avoid WASI)
REFC_C_FILES="$REFC_SRC/runtime.c $REFC_SRC/memoryManagement.c $REFC_SRC/stringOps.c $REFC_SRC/mathFunctions.c $REFC_SRC/casts.c $REFC_SRC/prim.c $REFC_SRC/refc_util.c"

# =============================================================================
# Step 3: Compile C → WASM (Emscripten)
# =============================================================================
echo ">>> Step 3: C → WASM (Emscripten)"

emcc "$C_FILE" \
    $REFC_C_FILES \
    "$MINI_GMP/mini-gmp.c" \
    "$IC0_SUPPORT/ic0_stubs.c" \
    "$IC0_SUPPORT/canister_entry.c" \
    "$IC0_SUPPORT/wasi_stubs.c" \
    -I"$REFC_INCLUDE" \
    -I"$C_INCLUDE" \
    -I"$MINI_GMP" \
    -I"$IC0_SUPPORT" \
    -o "$BUILD_DIR/ouc.wasm" \
    -s STANDALONE_WASM=1 \
    -s FILESYSTEM=0 \
    -s ERROR_ON_UNDEFINED_SYMBOLS=0 \
    --no-entry \
    -O2 \
    2>&1 || {
    echo "Emscripten compilation failed"
    exit 1
}

echo ">>> Step 4: WASI stubbing"

# Check if stub-wasi.sh exists in idris2-wasm or create inline
STUB_WASI="$PROJECT_DIR/../idris2-wasm/tools/stub-wasi.sh"
if [ ! -f "$STUB_WASI" ]; then
    # Inline WASI stubbing using wabt
    if command -v wasm2wat >/dev/null 2>&1 && command -v wat2wasm >/dev/null 2>&1; then
        echo "Stubbing WASI imports..."
        wasm2wat "$BUILD_DIR/ouc.wasm" -o "$BUILD_DIR/ouc.wat"

        # Replace WASI imports with stub functions
        sed -i.bak '
            s/(import "wasi_snapshot_preview1" "fd_close" (func $fd_close (type [0-9]*)))/(func $fd_close (param i32) (result i32) i32.const 0)/
            s/(import "wasi_snapshot_preview1" "fd_write" (func $fd_write (type [0-9]*)))/(func $fd_write (param i32 i32 i32 i32) (result i32) i32.const 0)/
            s/(import "wasi_snapshot_preview1" "fd_seek" (func $fd_seek (type [0-9]*)))/(func $fd_seek (param i32 i64 i32 i32) (result i32) i32.const 0)/
            s/(import "wasi_snapshot_preview1" "fd_read" (func $fd_read (type [0-9]*)))/(func $fd_read (param i32 i32 i32 i32) (result i32) i32.const 0)/
            s/(import "wasi_snapshot_preview1" "environ_sizes_get" (func $environ_sizes_get (type [0-9]*)))/(func $environ_sizes_get (param i32 i32) (result i32) i32.const 0)/
            s/(import "wasi_snapshot_preview1" "environ_get" (func $environ_get (type [0-9]*)))/(func $environ_get (param i32 i32) (result i32) i32.const 0)/
            s/(import "wasi_snapshot_preview1" "proc_exit" (func $proc_exit (type [0-9]*)))/(func $proc_exit (param i32))/
        ' "$BUILD_DIR/ouc.wat"

        wat2wasm "$BUILD_DIR/ouc.wat" -o "$BUILD_DIR/ouc_stubbed.wasm" || {
            echo "WASI stubbing failed, using original WASM"
            cp "$BUILD_DIR/ouc.wasm" "$BUILD_DIR/ouc_stubbed.wasm"
        }
    else
        echo "wabt not found, skipping WASI stubbing"
        cp "$BUILD_DIR/ouc.wasm" "$BUILD_DIR/ouc_stubbed.wasm"
    fi
else
    bash "$STUB_WASI" "$BUILD_DIR/ouc.wasm" "$BUILD_DIR/ouc_stubbed.wasm"
fi

# =============================================================================
# Done
# =============================================================================
echo ">>> Build complete!"
echo ""
echo "Output files:"
ls -la "$BUILD_DIR/ouc.wasm" "$BUILD_DIR/ouc_stubbed.wasm" 2>/dev/null || ls -la "$BUILD_DIR/ouc.wasm"

# Show WASM info if wabt tools available
if command -v wasm-objdump >/dev/null 2>&1; then
    echo ""
    echo "=== WASM Exports ==="
    wasm-objdump -x "$BUILD_DIR/ouc_stubbed.wasm" 2>/dev/null | grep -E "Export\[|^ - func" | head -30 || true

    echo ""
    echo "=== WASM Imports ==="
    wasm-objdump -x "$BUILD_DIR/ouc_stubbed.wasm" 2>/dev/null | grep -E "Import\[|^ - func" | head -20 || true
fi

echo ""
echo "Next steps:"
echo "  1. Copy to dfx project: cp $BUILD_DIR/ouc_stubbed.wasm <dfx-project>/ouc.wasm"
echo "  2. Configure dfx.json with custom WASM path"
echo "  3. Deploy: dfx deploy --network local"
