#!/bin/bash
# OUC E2E Local Deployment Script
# Deploys OUC canister + Dashboard frontend to local dfx replica

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
UI_DIR="$PROJECT_DIR/../idris2-ouc-ui"

echo "=== OUC E2E Local Deployment ==="
echo "Project: $PROJECT_DIR"
echo "UI Dir:  $UI_DIR"

# 1. Check prerequisites
echo ""
echo "[1/6] Checking prerequisites..."
command -v dfx >/dev/null 2>&1 || { echo "Error: dfx not installed"; exit 1; }
command -v npm >/dev/null 2>&1 || { echo "Error: npm not installed"; exit 1; }

# 2. Build OUC WASM
echo ""
echo "[2/6] Building OUC canister..."
cd "$PROJECT_DIR"
if [ ! -f "build/ouc_stubbed.wasm" ]; then
    echo "  OUC WASM not found. Run 'make build' first."
    exit 1
fi
echo "  OUC WASM: build/ouc_stubbed.wasm"

# 3. Build UI
echo ""
echo "[3/6] Building Dashboard UI..."
cd "$UI_DIR"
npm run build:idris
cp build/exec/oucdashboard dist/oucdashboard.js
npx esbuild src/indexer.js --bundle --format=iife --global-name=oucIndexerModule --outfile=dist/indexer.js
echo "  Dashboard built: dist/"

# 4. Start dfx (if not running)
echo ""
echo "[4/6] Starting dfx replica..."
cd "$PROJECT_DIR"
if ! dfx ping --network local >/dev/null 2>&1; then
    dfx start --clean --background
    sleep 3
fi
echo "  dfx replica running"

# 5. Deploy canisters
echo ""
echo "[5/6] Deploying canisters..."
dfx deploy --network local

# 6. Extract canister IDs
echo ""
echo "[6/6] Canister IDs:"
OUC_CANISTER_ID=$(dfx canister id ouc --network local)
DASHBOARD_CANISTER_ID=$(dfx canister id ouc_dashboard --network local)

echo "  OUC:       $OUC_CANISTER_ID"
echo "  Dashboard: $DASHBOARD_CANISTER_ID"

# Write .env file
cat > "$PROJECT_DIR/.env.local" << EOF
# Generated by deploy-local.sh
OUC_CANISTER_ID=$OUC_CANISTER_ID
DASHBOARD_CANISTER_ID=$DASHBOARD_CANISTER_ID
DFX_NETWORK=local
EOF

echo ""
echo "=== Deployment Complete ==="
echo ""
echo "Dashboard URL: http://$DASHBOARD_CANISTER_ID.localhost:4943"
echo "OUC Candid:    http://127.0.0.1:4943/?canisterId=$OUC_CANISTER_ID"
echo ""
echo "Test commands:"
echo "  dfx canister call ouc getVersion"
echo "  dfx canister call ouc getAuditors"
echo "  dfx canister call ouc getSubscription"
echo "  dfx canister call ouc getTreasury"
